// <auto-generated />
using System;
using CvarcLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvarcLogger.Data.Migrations
{
    [DbContext(typeof(CvarcLoggerDbContext))]
    [Migration("20260825230438_AddSkccFieldsToQso")]
    partial class AddSkccFieldsToQso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("CvarcLogger.Core.Models.ContestSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCountry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStateProvince")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryAssisted")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryBand")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryOperator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryOverlay")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryPower")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryStation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryTransmitter")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedScore")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContestId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operators")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoapBox")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ModifiedAtUtc");

                    b.ToTable("ContestSubmissions");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.DxccEntity", b =>
                {
                    b.Property<int>("EntityCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CqZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItuZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityCode");

                    b.ToTable("DxccEntities");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.PotaActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQsoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PotaActivations");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.PrefixMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DxccEntityCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DxccEntityCode");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("PrefixMappings");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.Qso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdifExtraFieldsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrlSection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Check")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CqZone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DxccEntityCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DxccEntityOverride")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FrequencyMhz")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FrequencyRxMhz")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItuZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotwQslRcvd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LotwQslRcvdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotwQslSent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LotwQslSentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyGridSquare")
                        .HasColumnType("TEXT");

                    b.Property<string>("MySigInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MySkccNr")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MySotaRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ObservesDaylightSavingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Op")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Precedence")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("QslRcvd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QslRcvdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QslSent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QslSentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QslViaCallsign")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QsoDateTimeOffUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QsoDateTimeOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qth")
                        .HasColumnType("TEXT");

                    b.Property<string>("RstRcvd")
                        .HasColumnType("TEXT");

                    b.Property<string>("RstSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SigInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkccNr")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SotaRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SrxSerial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StxSerial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubMode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TxPowerWatts")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UtcOffsetHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Callsign");

                    b.HasIndex("DxccEntityCode");

                    b.HasIndex("QsoDateTimeOnUtc");

                    b.HasIndex("StationProfileId");

                    b.ToTable("Qsos");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.SkccMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberNumber")
                        .HasColumnType("TEXT");

                    b.Property<char?>("MemberStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SkccMembers");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.SotaActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SotaActivations");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.StationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyGridSquare")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ObservesDaylightSavingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Op")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qth")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkccNr")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UtcOffsetHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StationProfiles");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.PrefixMapping", b =>
                {
                    b.HasOne("CvarcLogger.Core.Models.DxccEntity", "DxccEntity")
                        .WithMany("Prefixes")
                        .HasForeignKey("DxccEntityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DxccEntity");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.Qso", b =>
                {
                    b.HasOne("CvarcLogger.Core.Models.DxccEntity", "DxccEntity")
                        .WithMany()
                        .HasForeignKey("DxccEntityCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CvarcLogger.Core.Models.StationProfile", "StationProfile")
                        .WithMany()
                        .HasForeignKey("StationProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DxccEntity");

                    b.Navigation("StationProfile");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.DxccEntity", b =>
                {
                    b.Navigation("Prefixes");
                });
#pragma warning restore 612, 618
        }
    }
}
