// <auto-generated />
using System;
using CvarcLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvarcLogger.Data.Migrations
{
    [DbContext(typeof(CvarcLoggerDbContext))]
    [Migration("20260715204055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("CvarcLogger.Core.Models.DxccEntity", b =>
                {
                    b.Property<int>("EntityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CqZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItuZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityCode");

                    b.ToTable("DxccEntities");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.PrefixMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DxccEntityCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DxccEntityCode");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("PrefixMappings");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.Qso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdifExtraFieldsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CqZone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DxccEntityCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DxccEntityOverride")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FrequencyMhz")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FrequencyRxMhz")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItuZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotwQslRcvd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LotwQslRcvdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotwQslSent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LotwQslSentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyGridSquare")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("QslRcvd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QslRcvdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QslSent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QslSentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QslViaCallsign")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QsoDateTimeOffUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QsoDateTimeOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RstRcvd")
                        .HasColumnType("TEXT");

                    b.Property<string>("RstSent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SrxSerial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StxSerial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubMode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TxPowerWatts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Callsign");

                    b.HasIndex("DxccEntityCode");

                    b.HasIndex("QsoDateTimeOnUtc");

                    b.HasIndex("StationProfileId");

                    b.ToTable("Qsos");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.StationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyGridSquare")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorCallsign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StationProfiles");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.PrefixMapping", b =>
                {
                    b.HasOne("CvarcLogger.Core.Models.DxccEntity", "DxccEntity")
                        .WithMany("Prefixes")
                        .HasForeignKey("DxccEntityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DxccEntity");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.Qso", b =>
                {
                    b.HasOne("CvarcLogger.Core.Models.DxccEntity", "DxccEntity")
                        .WithMany()
                        .HasForeignKey("DxccEntityCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CvarcLogger.Core.Models.StationProfile", "StationProfile")
                        .WithMany()
                        .HasForeignKey("StationProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DxccEntity");

                    b.Navigation("StationProfile");
                });

            modelBuilder.Entity("CvarcLogger.Core.Models.DxccEntity", b =>
                {
                    b.Navigation("Prefixes");
                });
#pragma warning restore 612, 618
        }
    }
}
