using CvarcLogger.Core.Adif;
using CvarcLogger.Core.Models;

namespace CvarcLogger.Tests;

public class AdifRoundTripTests
{
    [Fact]
    public void RoundTrip_PreservesCoreFields()
    {
        var qso = new Qso
        {
            Callsign = "W1AW",
            QsoDateTimeOnUtc = new DateTime(2026, 6, 1, 14, 30, 0, DateTimeKind.Utc),
            Band = "20m",
            Mode = "SSB",
            FrequencyMhz = 14.250m,
            RstSent = "59",
            RstRcvd = "57",
            Name = "Hiram",
            GridSquare = "FN31",
            City = "Newington",
            State = "CT",
            Country = "United States",
            ArrlSection = "CT",
            CqZone = 5,
            ItuZone = 8,
            StationCallsign = "N0CALL",
            Comment = "Test contact",
            QslSent = QslStatus.Sent,
            QslRcvd = QslStatus.NotSent,
        };

        var record = AdifFieldMapper.ToAdifRecord(qso);
        var writer = new StringWriter();
        AdifWriter.WriteRecord(writer, record);

        var parsedRecords = AdifReader.ReadAll(writer.ToString());
        Assert.Single(parsedRecords);

        var roundTripped = AdifFieldMapper.ToQso(parsedRecords[0]);

        Assert.Equal(qso.Callsign, roundTripped.Callsign);
        Assert.Equal(qso.QsoDateTimeOnUtc, roundTripped.QsoDateTimeOnUtc);
        Assert.Equal(qso.Band, roundTripped.Band);
        Assert.Equal(qso.Mode, roundTripped.Mode);
        Assert.Equal(qso.FrequencyMhz, roundTripped.FrequencyMhz);
        Assert.Equal(qso.RstSent, roundTripped.RstSent);
        Assert.Equal(qso.RstRcvd, roundTripped.RstRcvd);
        Assert.Equal(qso.Name, roundTripped.Name);
        Assert.Equal(qso.GridSquare, roundTripped.GridSquare);
        Assert.Equal(qso.City, roundTripped.City);
        Assert.Equal(qso.State, roundTripped.State);
        Assert.Equal(qso.Country, roundTripped.Country);
        Assert.Equal(qso.ArrlSection, roundTripped.ArrlSection);
        Assert.Equal(qso.CqZone, roundTripped.CqZone);
        Assert.Equal(qso.ItuZone, roundTripped.ItuZone);
        Assert.Equal(qso.StationCallsign, roundTripped.StationCallsign);
        Assert.Equal(qso.Comment, roundTripped.Comment);
        Assert.Equal(qso.QslSent, roundTripped.QslSent);
        Assert.Equal(qso.QslRcvd, roundTripped.QslRcvd);
    }

    [Fact]
    public void Reader_ParsesMultiLineCommentByLength_NotByLineBreaks()
    {
        string multilineComment = "Line one\r\nLine two\r\nLine three";
        string adif = $"<CALL:4>TEST<COMMENT:{multilineComment.Length}>{multilineComment}<EOR>";

        var records = AdifReader.ReadAll(adif);

        Assert.Single(records);
        Assert.Equal("TEST", records[0].Get("CALL"));
        Assert.Equal(multilineComment, records[0].Get("COMMENT"));
    }

    [Fact]
    public void Reader_HandlesHeaderlessFile()
    {
        string adif = "<CALL:4>TEST<BAND:3>20m<EOR>";

        var records = AdifReader.ReadAll(adif);

        Assert.Single(records);
        Assert.Equal("TEST", records[0].Get("CALL"));
        Assert.Equal("20m", records[0].Get("BAND"));
    }

    [Fact]
    public void Reader_DiscardsHeaderFieldsBeforeEoh()
    {
        string adif = "Generated by Test\r\n<ADIF_VER:5>3.1.4<PROGRAMID:9>CvarcLogger<EOH>\r\n<CALL:4>TEST<EOR>";

        var records = AdifReader.ReadAll(adif);

        Assert.Single(records);
        Assert.Equal("TEST", records[0].Get("CALL"));
        Assert.Null(records[0].Get("ADIF_VER"));
        Assert.Null(records[0].Get("PROGRAMID"));
    }

    [Fact]
    public void UnknownField_RoundTripsThroughExtraFieldsJson()
    {
        string adif = "<CALL:4>TEST<BAND:3>20m<MY_RIG:7>IC-7300<EOR>";
        var records = AdifReader.ReadAll(adif);
        var qso = AdifFieldMapper.ToQso(records[0]);

        Assert.NotNull(qso.AdifExtraFieldsJson);
        Assert.Contains("MY_RIG", qso.AdifExtraFieldsJson);

        var record = AdifFieldMapper.ToAdifRecord(qso);
        Assert.Equal("IC-7300", record.Get("MY_RIG"));
    }

    [Fact]
    public void WriteAll_ProducesParsableFileWithHeader()
    {
        var qsos = new List<Qso>
        {
            new() { Callsign = "AA1AA", Band = "40m", Mode = "CW", StationCallsign = "N0CALL", QsoDateTimeOnUtc = DateTime.UtcNow },
            new() { Callsign = "BB2BB", Band = "15m", Mode = "FT8", StationCallsign = "N0CALL", QsoDateTimeOnUtc = DateTime.UtcNow },
        };

        var writer = new StringWriter();
        AdifWriter.WriteAll(writer, qsos.Select(AdifFieldMapper.ToAdifRecord));

        var parsed = AdifReader.ReadAll(writer.ToString());

        Assert.Equal(2, parsed.Count);
        Assert.Equal("AA1AA", parsed[0].Get("CALL"));
        Assert.Equal("BB2BB", parsed[1].Get("CALL"));
    }
}
